### ISSUE TITLE
Hw 95 Feedback # 1

### ISSUE THREAD

**Issue by jmai28** [tangym27/TangyBahanna#2]
For the first three sections, I find no problem with them. Those sections were already given away in class.
However, for your pseudo code,  you have

Else if e is on a wall
      Return 

I for one, think that the base case should return false. As if you were to start on a wall, there is no way to get to the treasure. Your recursive abstraction already checks if the next possible spaces are legal spaces to invoke the recursive abstraction on. Hence, you do not have to fear the recursive abstraction accidentally invoking the return false.

For the next part in your code I see

      For each possible direction
        Move e in the direction
        if wall
          move e back
        else
          Invoke recursive abstraction
    return false

I think you should also check if the possible spaces to move to, are out of the maze. Though I'm not sure if Mr. Holmes' code takes care of it.

The last comment I have is a suggestion. I think that your pseudo code should include code for dropping walls. As your pseudo code checks for every possible space, this can prevent infinite loops from occurring.

**Comment by tangym27** [comment]
Thank you for taking the time to read through our issue and provide thoughtful comments in response.
We have fixed the issue to the best of our knowledge and ability. Please reopen if you think otherwise.

**Comment by jmai28** [comment]
The code as it is now

      For each possible direction
         Move e in the direction
         if (invoke recursion abstraction)
            return true
         place wall at the current position
         move e back (go back to snapshot)
      return false

I think it should be

      Place wall at the current position
      For each possible direction
         Move e in the direction
           if isLegal is true //  isLegal was one of the given methods
             invoke recursion abstraction
         move e back (go back to snapshot)
      return false

The wall is placed on the current position so that the next recursive abstraction will not move the explorer backward. Only backtracking will bring the explorer back to the previous space. When backtracking does that, it will not matter that there is a wall on the space.

There is also no need to return true in your recursive abstraction as the base case will return true when needed.

**Comment by hyang66** [comment]
Thank you for raising these issues! 
I agree with the moving of the line of code that places a wall down, but I believe it is okay just to invoke the recursive abstraction without checking for anything with an if statement, which is what I believe to be an alternate solution to the problem, which is related to your last sentence.
If you disagree with any of these changes, feel free to reopen this issue :)

**Comment by hyang66** [comment]
Looking back on your comments, I've realized that they are correct, and my edits were wrong; sorry about that and thank you once again!
